Bump graphiql and add support to v2 configurations
HSLdevcom/graphiql-deployment pull request #49
Opened 2022-08-15 12:09 UTC by joonaojapalo

Changes:
 - fix broken build (yarn start) in master by graphiql version bump
 - add v2 router configurations
 - handle use cases eg. when user changes API version to production but such router eg. prodiction/hsl v2 doesn't exist

Related issue: DT-5292

2022-08-18 07:54 UTC, optionsome requested changes
Typing something in the query seems to cause rerender and new requests to be sent which also affects how the autocomplete works.

2022-08-18 10:44 UTC, joonaojapalo commented
Autocomplete flickering issue solved.

2022-08-18 11:26 UTC, optionsome reviewed
I think it's better to call the APIs v1/v2 instead of otp1, otp2 because I think we will end up with a v3 that also uses otp2.

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'HSL (otp1)',
```suggestion
        title: 'HSL (v1)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'HSL (otp2)',
```suggestion
        title: 'HSL (v2)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'Waltti (otp1)',
```suggestion
        title: 'Waltti (v1)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'Waltti (otp2)',
```suggestion
        title: 'Waltti (v2)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'Waltti alt. (otp2)',
```suggestion
        title: 'Waltti alt. (v2)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'Finland (otp1)',
```suggestion
        title: 'Finland (v1)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'Finland (otp2)',
```suggestion
        title: 'Finland (v2)',
```

2022-08-18 11:26 UTC, optionsome commented on src/App.js
> +        title: 'VARELY (otp2)',
```suggestion
        title: 'VARELY (v2)',
```

2022-09-05 06:43 UTC, optionsome commented on src/App.js
> +        title: 'HSL (otp1)',
```suggestion
        title: 'HSL (v2)',
```

2022-09-05 07:41 UTC, optionsome approved these changes

2022-09-05 07:41 UTC, merged